### ISSUE TITLE
Add `hatch-vcs`?

### ISSUE THREAD

**Issue by Saransh-cpp** [scientific-python/cookie#243]
I have been using `cookie` for `hatch` projects recently, but I could not find an option to include `hatch-vcs` using the CLI. The `setuptools` backend includes `setuptools_scm` by default, should the `hatchling` backend include `hatch-vcs` by default too or is it not included intentionally? Thanks!

Edit: `hatch-vcs` is mentioned in the guide, but not included in `cookie`.

**Comment by henryiii** [comment]
I've actually partially started on adding a true/false choice, `vcs`. It just turned out to be quite a bit of work to add it to all backends at once, especially some that don't support it well or at all. I removed trampolim a few days ago to help, and I might drop whey. The problem currently would be meson-python; I'd like to get `dynamic-metadata` finished so we can try adding it there.

Cookiecutter supports bools now, and in `copier`, it can be really nice with `when:`. I'm thinking about proposing `__when__` to cookiecutter. Then I could just hide the option when it's not supported. :)

**Comment by Saransh-cpp** [comment]
Ah, good to know this is already being worked upon :)

I see, not every backend has a corresponding `vcs` plugin or library. The last time I was here, the only method to run cookie locally was cookiecutter, but everything has evolved a lot now.

Let me know if I can help in any way! Feel free to close this issue, or generalise it for every backend.
