### ISSUE TITLE
No license metadata in pyproject.toml with cookiecutter

### ISSUE THREAD

**Issue by fconil** [scientific-python/cookie#319]
Hi,
Thank for your great guide and these templates, it very useful and I discovered many things (copier, cruft, flit_scm, ...).

I am trying to compare several backends and I have generated project templates with "Hatchling", "Flit-core" and "Setuptools with pyproject.toml".
I left the default BSD license for all.

No template has a `license` metadata in the `[project]` table of the `pyproject.toml` file.
There is a classifier `License :: OSI Approved :: BSD License`.

When the wheel is build with Flit, it contains no LICENSE file.

Here is what I did for the "Hatchling" backend :

```bash
$ cookiecutter gh:scientific-python/cookie
  [1/9] The name of your project (package): my_scientific_package
  [2/9] The name of your (GitHub?) org (org): mylogin
  [3/9] The url to your GitHub or GitLab repository (https://github.com/mylogin/my_scientific_package):
  [4/9] Your name (My Name): My full name
  [5/9] Your email (me@email.com): myadress@email.com
  [6/9] A short description of your project (A great package.): Testing the scientific templates for different backends
  [7/9] Select a license
    1 - BSD
    2 - Apache
    3 - MIT
    Choose from [1/2/3] (1):
  [8/9] Choose a build backend
    1 - Hatchling                      - Pure Python (recommended)
    2 - Flit-core                      - Pure Python (minimal)
    3 - PDM-backend                    - Pure Python
    4 - Whey                           - Pure Python
    5 - Poetry                         - Pure Python
    6 - Setuptools with pyproject.toml - Pure Python
    7 - Setuptools with setup.py       - Pure Python
    8 - Setuptools and pybind11        - Compiled C++
    9 - Scikit-build-core              - Compiled C++ (recommended)
    10 - Meson-python                  - Compiled C++ (also good)
    11 - Maturin                       - Compiled Rust (recommended)
    Choose from [1/2/3/4/5/6/7/8/9/10/11] (1):
  [9/9] Use version control for versioning [y/n] (y):
```

**Comment by henryiii** [comment]
The canonical location for license metadata is your trove classifiers. The "license" field doesn't really mean anything, and some backends completely ignore it (like flit). It doesn't map to the License metadata field; that field ([since 2005](https://peps.python.org/pep-0345/#license-optional), also see [2003](https://peps.python.org/pep-0314/#license) which was similar) is only for cases not covered by the classifiers, and is basically a free form field supposed to "describe deviations from the standard licenses". [PEP 639](https://peps.python.org/pep-0639/) is designed to fix this, but it's not accepted yet.

Flit is supposed to automatically capture all `"LICEN[SC]E*"` files. But you are correct, it does seem to be missing.

**Comment by henryiii** [comment]
Actually, the search is https://github.com/pypa/flit/blob/ee17c70cdef4c9bd2f1d076f2dd8aacabdd38098/flit_core/flit_core/wheel.py#L185. This is a known quirk/issue: https://github.com/pypa/flit/issues/379.

We can either add `license.file`, or add a SDist include section.
